name: hugo-cms
version: 0.2.2
description: CMS
# The go package of the service, required for the go source generation.
# Leave it blank if use only chart generation.
# package: gkgen/sample

# # External services
# external:
#   metric: graphite.default.svc.cluster.local:2003

# # The go package of the service, required for the go source generation.
# # Leave `http`, `proxy` blank to disable it.
# # Or leave all blank if use only chart generation.
# port:
#   grpc: 8080
#   proxy: 8081
#   http: 8082
#   # ws: 8083
#   # your-port, if you want include it in `base/config.go`
